# Generated by Django 4.0.3 on 2022-06-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, '@moderator'), (1, 'Like'), (2, 'Comment')], verbose_name='Тип'),
        ),
    ]
