# Generated by Django 4.0.3 on 2022-07-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_account', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='article',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id комментария/поста'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(0, '@moderator'), (1, 'Like_Article'), (2, 'Comment'), (3, 'Like_Comment')], verbose_name='Тип'),
        ),
    ]
