# Generated by Django 4.0.3 on 2022-06-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_article_is_active_category_is_active_and_more'),
        ('mainapp', '0004_article_likes_alter_comment_body'),
    ]

    operations = [
    ]
