# Generated by Django 4.0.3 on 2022-06-21 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_merge_20220617_2129'),
        ('mainapp', '0005_merge_20220620_2022'),
    ]

    operations = [
    ]
