# Generated by Django 4.0.3 on 2022-06-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_merge_20220618_0611'),
        ('mainapp', '0006_merge_20220621_2152'),
    ]

    operations = [
    ]
