# Generated by Django 4.0.3 on 2022-06-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_comment_options_comment_parent'),
        ('mainapp', '0006_merge_20220621_2152'),
    ]

    operations = [
    ]
