# Generated by Django 4.0.3 on 2022-06-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_comment_options_comment_parent'),
        ('mainapp', '0008_alter_article_category_alter_article_tag_and_more'),
    ]

    operations = [
    ]
