# Generated by Django 4.0.3 on 2022-06-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_20220622_0831'),
        ('mainapp', '0009_merge_20220624_1605'),
    ]

    operations = [
    ]
