# Generated by Django 4.0.3 on 2022-06-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_merge_20220622_2117'),
        ('mainapp', '0008_comment_is_parent'),
        ('mainapp', '0010_merge_20220624_1608'),
    ]

    operations = [
    ]
